version: "3"

services:
  app:
    build:
      context: .
    mem_limit: 400m
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=webapp-hotel
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - postgres-booking
    depends_on:
      - postgres

  postgres:
    container_name: postgres-booking
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres-booking:/data/postgres-booking
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=webapp-hotel
    networks:
      - postgres-booking
 
  pgadmin:
    links:
      - postgres:postgres-booking
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - postgres-booking
    depends_on:
      - postgres
 
networks:
  postgres-booking:
    driver: bridge