version: "3"

services:
  postgres:
    container_name: postgres-hotel
    image: postgres:15
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres-hotel:/data/postgres-hotel
    env_file:
    - docker.env
    networks:
    - postgres-hotel
 
  pgadmin:
    links:
    - postgres:postgres-hotel
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "5050:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres-hotel
 
networks:
  postgres-hotel:
    driver: bridge